name: cityfury
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- django=1.11.3=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.0=0
- pytz=2017.2=py36_0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - django-appconf==1.0.2
  - django-select2==6.0.0
  - sorl-thumbnail==12.4.1
